### PR TITLE
REC-78: Home page redesign

### PR DESCRIPTION
**Pull request by philipedberg**

### CODE REVIEW

**Comment by philipedberg** [comment]
https://user-images.githubusercontent.com/65982406/226908510-d6566cc3-4209-44bd-907f-3d1aabfc2548.mov

**Comment by Jonsson01** [comment]
Super trooper nice pliancy my boy! But one test did not go through

**Comment by Jonsson01** [comment]
Perfektomundo!

**Comment by Jonsson01** [comment]
Oops wrong button

**Review by Lafelix — APPROVED** [review]
Good job 😍

**Pull request merged**
